spring.application.name=HealthcareTP

# MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://180.210.82.240:3306/healthcare_db
spring.datasource.username=root
spring.datasource.password=

# DATABASE
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:~/local
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
#마리아디비
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
#h2
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

# 유휴 연결 최소 유지 수 (네트워크 부하 줄임)
#spring.datasource.hikari.minimum-idle=5 
# 커넥션 풀이 DB 연결을 유지할 최대 시간 설정 (DB의 wait_timeout보다 짧게 설정)
#spring.datasource.hikari.max-lifetime=580000 
# 연결 획득 시 유효성 검사 (기본값 true이지만 명시 가능)
#spring.datasource.hikari.auto-commit=false 

#properties logging.level.org.springframework=DEBUG debug=true



#### application-prod.properties 내용
### 1. 포트 설정 (HTTPS 표준 포트인 443 추천)
### 2. SSL 설정 활성화
### 3. 키스토어 파일 경로
## 프로젝트 내부(resources)에 뒀다면: classpath:keystore.p12
## 서버 절대 경로에 뒀다면: /home/ubuntu/conf/keystore.p12
### 4. 키스토어 형식 (PKCS12)
### 5. 키스토어 비밀번호 (openssl로 .p12 만들 때 입력한 비밀번호)
### 6. 별칭 (openssl 명령어에서 -name 뒤에 썼던 값, 예: tomcat)

## 포트 설정
server.port=8080

## 터미널 칼라 출력
spring.output.ansi.enabled=ALWAYS

## 로깅
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n

## 파일 업로드
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

## 정적 리소스에 대해 캐시 사용 안함
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

## OpenAI
spring.ai.openai.api-key=
